export default {
    user: {name: 'convidado', role: 'subscriber'},
    table: null,
    channel: null,
    titles: null,
    titles_channel: null,
    title: null,
    ms_title: null,
    page: 1,
    per_page: 10,
    letters: null,
    letter: null,
    header_aux: null,
    resetSort: 0,
}
